name: timetide
description: AI-Powered Daily Task Planner and Reminder App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_storage: ^12.3.4  # UI and animations
  lottie: ^3.1.2
  cached_network_image: ^3.4.0
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.2
  # PDF generation
  pdf: ^3.11.1
  path_provider: ^2.1.5
  open_file: ^3.5.9
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.0
  # Fonts
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  # Drag-and-drop
  reorderables: ^0.6.0
  # Data
  shared_preferences: ^2.3.0
  http: ^1.2.1
  # Image picker
  image_picker: ^1.1.2  # Added for avatar selection  # Charts
  fl_chart: ^0.68.0
  # Gemini API
  flutter_dotenv: ^5.1.0
  # Internationalization
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/fonts/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700